### ISSUE TITLE
Having trouble installing this on Mac

### ISSUE THREAD

**Issue by springcoil** [tmadl/sklearn-expertsys#1]
Has anyone tried to install this on Mac. Is there any alternative to PyFIM?

**Comment by tmadl** [comment]
Hi, I can't test this as I don't have a Mac, but have you tried installing PyFIM from source? from http://www.borgelt.net/pyfim.html ? Download the zip/tar.gz file (depending on whether your OS is 32 or 64 bit) and then run 
python setup_fim.py install
(may need sudo rights). Then try "import fim" in a python shell. That should do it.

**Comment by springcoil** [comment]
That didn't work due to a GCC error.

On Tue, Feb 23, 2016 at 6:10 PM, Tamas Madl notifications@github.com
wrote:

> Hi, I can't test this as I don't have a Mac, but have you tried installing
> PyFIM from source? from http://www.borgelt.net/pyfim.html ? Download the
> zip/tar.gz file (depending on whether your OS is 32 or 64 bit) and then run
> python setup_fim.py install
> (may need sudo rights). Then try "import fim" in a python shell. That
> should do it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tmadl/sklearn-expertsys/issues/1#issuecomment-187795300
> .

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by ghosthugger** [comment]
try installing gcc
brew install gcc

that worked for me on osX
