### ISSUE TITLE
continuous and categorical features together

### ISSUE THREAD

**Issue by zygmuntz** [tmadl/sklearn-expertsys#2]
When I use mixed data (a Pandas frame), I get `ValueError: could not convert string to float`. So I one-hot encode categoricals and I get `Warning: non-categorical data. Trying to discretize. (Please convert categorical values to strings to avoid this.)` Is it possible to have continuous and categorical features together in X?

**Comment by tmadl** [comment]
Hi, thanks for pointing this out!
I've just added the capability to use mixed data. Anything that is numeric is discretized (BOTH integers and floats), unless explicitly prevented by passing the parameter "undiscretized_features" to the .fit function.

One-hot encoding is not necessary nor beneficial - one of the advantages of Bayesian rule lists (apart from interpretability) is the straightforward use of categoricals. They should be left in as strings / non-numeric objects

I've also added a demo (examples.hepatitis_mixeddata_demo.py) illustrating the usage with mixed data

Btw, I enjoy reading FastML. Keep up the good work!
